In [2]:
import numpy as np
#question 1
#Write a Numpy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
vector_length = np.random.randint(low=0, high=11, size=5)

In [3]:
vector_length

array([3, 9, 6, 0, 1])

In [4]:
#question 2
#Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
vectors_values = np.arange(15,56)

In [5]:
vectors_values

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [10]:
vectors_values[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [16]:
#question 3
#Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. 
#creating the random array using random rand
random_array = np.random.rand(1000)

In [17]:
random_array

array([5.13035748e-01, 6.38546390e-01, 5.91450154e-01, 3.66078720e-01,
       3.37769644e-01, 8.79835697e-01, 4.50144789e-01, 5.66307925e-01,
       5.15593774e-01, 3.24023587e-01, 8.62773429e-01, 9.87305283e-01,
       3.54640843e-01, 7.16420370e-01, 8.64798566e-01, 1.40886079e-01,
       1.53533989e-01, 4.54963118e-01, 4.55406214e-01, 5.00611434e-01,
       3.81662778e-01, 5.94772337e-01, 9.42727210e-01, 5.10666105e-01,
       2.13098037e-01, 3.82950213e-01, 1.91190199e-01, 5.20992858e-01,
       7.21748020e-01, 5.01210298e-01, 8.74220274e-01, 3.07502472e-01,
       6.04091577e-02, 1.42685097e-02, 2.18491698e-01, 4.20981567e-02,
       8.22129278e-02, 8.65317345e-01, 6.63332641e-01, 7.87541932e-01,
       2.38868176e-02, 6.65488008e-01, 7.96775642e-01, 2.99456205e-01,
       1.72499677e-01, 5.01752039e-01, 6.11084411e-01, 6.48900635e-01,
       6.03632722e-01, 7.30769570e-01, 2.43799923e-01, 3.89763360e-01,
       8.16559153e-01, 5.20744307e-01, 6.32609962e-02, 4.74522514e-01,
      

In [18]:
# finding the mean of the array
avg_random_array = np.mean(random_array)

In [19]:
avg_random_array

0.4961752417363888

In [20]:
# finding the variance of the array.
var_random_array = np.var(random_array)

In [21]:
var_random_array

0.08373485071373751

In [22]:
#finding the standard deviation of the array
std_random_array = np.std(random_array)

In [23]:
std_random_array

0.28936974740587085

In [24]:
#question 4
#Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array. 
#creating a 3x3 array
arrayy = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [25]:
arrayy

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [30]:
#calaculating the cummulative sum of elements along a given axis (assume axis = 0)
cummusum_rows = np.cumsum(arrayy,axis=0)

In [31]:
cummusum_rows

array([[ 3,  2,  1],
       [ 9,  7,  5],
       [18, 15, 12]], dtype=int32)

In [34]:
# calaculating the cummulative sum of elements along a given axis(assume axis = 1)
cummumsum_col = np.cumsum(arrayy,axis=1)
cummumsum_col

array([[ 3,  5,  6],
       [ 6, 11, 15],
       [ 9, 17, 24]], dtype=int32)

In [38]:
#calculating the sum over rows for each of the 3 columns
sum_over_column = np.sum(arrayy, axis=0)
sum_over_column

array([18, 15, 12])

In [39]:
#sum over columns for each of the 2 rows
sum_over_rows = np.sum(arrayy, axis = 1)
sum_over_rows

array([ 6, 15, 24])

In [40]:
# question 5
#Write a NumPy program to compute the multiplication of two given matrixes. 
# using the sample matrix given in the question:
matrix1 = np.array([[1,0],[0,1]])
matrix2 = np.array([[1,2],[3,4]])

In [41]:
#creating a multiplication function using dot in numpy
multiplicate_result = np.dot(matrix1,matrix2)

In [43]:
print("the multiplication of the matrix is:\n" , multiplicate_result)

the multiplication of the matrix is:
 [[1 2]
 [3 4]]
